# Generated by Django 5.0.7 on 2024-09-27 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_realtimeprediction_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='PfSenseLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('action', models.CharField(max_length=10)),
                ('protocol_type', models.CharField(max_length=10)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.CharField(max_length=10)),
                ('dst_port', models.CharField(max_length=10)),
            ],
        ),
    ]
