# Generated by Django 5.0.7 on 2024-09-27 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_pfsenselog'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogPfSense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('action', models.CharField(max_length=255)),
                ('protocol_type', models.CharField(max_length=50)),
                ('src_ip', models.GenericIPAddressField()),
                ('dst_ip', models.GenericIPAddressField()),
                ('src_port', models.CharField(max_length=10)),
                ('dst_port', models.CharField(max_length=10)),
                ('interface', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='PfSenseLog',
        ),
    ]
